# Generated by Django 4.0.2 on 2022-07-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='desc',
            new_name='description',
        ),
    ]
